# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-08-07 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercalls',
            name='id',
        ),
        migrations.AlterField(
            model_name='usercalls',
            name='Username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
