# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2021-08-07 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_tutorial', '0002_auto_20210807_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercalls',
            name='Username',
            field=models.CharField(max_length=101, primary_key=True, serialize=False),
        ),
    ]
